### ISSUE TITLE
Add Aggregate functions

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/row-level-security-lua#103]
## Situation

The adapter doesn't support any aggregate function right now:
```
...ecurity-lua/src/main/lua/exasolvs/query_renderer.lua:415: E-VS-QR-1: Unable to render unknown SQL expression type "function_aggregate".
```

As a user I would like to use aggregate functions.

When the aggregate function are implemented we need to enable a disabled test: `test_query_renderer.test_single_group_aggregation_and_aggregation_function`

Update 2023-06-27: meanwhile we are using version 4.0.0 of the base library `virtual-schema-common-lua`, so RLS should be able to render aggregate functions. There is no point in duplicating all integration tests from EVSL. three of them should be sufficient.

## Acceptance Criteria

* Three Aggregate function tests show that the functions from the base library are available in RLS
* Capability list is updated

**Comment by redcatbear** [comment]
Closed with #131.
