### ISSUE TITLE
Use system properties to set DEBUG_ADDRESS and LOG_LEVEL

### ISSUE THREAD

**Issue by ckunki** [exasol/row-level-security-lua#126]
[AbstractLuaVirtualSchemaIT.java](https://github.com/exasol/row-level-security-lua/blob/b6ea5b86eba5850c869aacfdb2bfcbdf39acc08c/src/test/java/com/exasol/AbstractLuaVirtualSchemaIT.java) sets `DEBUG_ADDRESS` and `LOG_LEVEL`.

```java
mergedProperties.put("DEBUG_ADDRESS", debugAddress);
mergedProperties.put("LOG_LEVEL", "TRACE");
```

Please check if using system properties supported by https://github.com/exasol/test-db-builder-java/issues/103 would make sense here.

**Comment by kaklakariada** [comment]
This is already implemented in https://github.com/exasol/row-level-security-lua/blob/main/src/test/java/com/exasol/AbstractLuaVirtualSchemaIT.java#L76
